// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using eAuction.Data;

namespace eAuction.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230427174049_FixUrl")]
    partial class FixUrl
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("eAuction.Models.DigitalGoods", b =>
                {
                    b.Property<int>("LotNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Condition")
                        .HasColumnType("text");

                    b.Property<int>("DigitalCategory")
                        .HasColumnType("integer");

                    b.Property<string>("Discription")
                        .HasColumnType("text");

                    b.Property<string>("ProductPicURL")
                        .HasColumnType("text");

                    b.Property<double>("StartBidPrice")
                        .HasColumnType("double precision");

                    b.HasKey("LotNumber");

                    b.ToTable("DigitalGood");
                });

            modelBuilder.Entity("eAuction.Models.Products", b =>
                {
                    b.Property<int>("LotNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Brand")
                        .HasColumnType("text");

                    b.Property<string>("Condition")
                        .HasColumnType("text");

                    b.Property<string>("Discription")
                        .HasColumnType("text");

                    b.Property<int>("ProductCategory")
                        .HasColumnType("integer");

                    b.Property<string>("ProductPicURL")
                        .HasColumnType("text");

                    b.Property<double>("StartBidPrice")
                        .HasColumnType("double precision");

                    b.HasKey("LotNumber");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("eAuction.Models.Services", b =>
                {
                    b.Property<int>("LotNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Discription")
                        .HasColumnType("text");

                    b.Property<string>("ProductPicURL")
                        .HasColumnType("text");

                    b.Property<int>("ServiceCategory")
                        .HasColumnType("integer");

                    b.Property<double>("StartBidPrice")
                        .HasColumnType("double precision");

                    b.Property<int>("YearsOfExpirience")
                        .HasColumnType("integer");

                    b.HasKey("LotNumber");

                    b.ToTable("Service");
                });

            modelBuilder.Entity("eAuction.Models.Vehicle", b =>
                {
                    b.Property<int>("LotNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Discription")
                        .HasColumnType("text");

                    b.Property<string>("Make")
                        .HasColumnType("text");

                    b.Property<string>("Model")
                        .HasColumnType("text");

                    b.Property<string>("ProductPicURL")
                        .HasColumnType("text");

                    b.Property<double>("StartBidPrice")
                        .HasColumnType("double precision");

                    b.Property<int>("VehicleCategory")
                        .HasColumnType("integer");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("LotNumber");

                    b.ToTable("Vehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
